### PR TITLE
feat(server): restrict access to whitelisted users

### LINKED ISSUE #128: I want to join chronicle with a valid mozilla.com email address

### PR DESCRIPTION
**Pull request by 6a68**
Currently returning a 401 with a nice error string, we could do more.

Fixes #128.

### CODE REVIEW

**Comment by 6a68** [comment]
Current error looks like:

screenshot 2015-02-23 09 17 27

We could certainly do more, but this works for now.

**Comment by 6a68** [comment]
@nchapman r?

@pdehaan The new lint-before-push code seemed to work quite nicely ^_^

**Comment by 6a68** [comment]
Note that this pull request does not specify what set of emails we are allowing for right now, but not using a regex does imply that it's a whitelist and not a generic "all at mozilla.com" or whatever. When we get to a "friends and family" beta release, we can update this to allow whole domains, if we want.

**Comment by 6a68** [comment]
Not sure if travis is perma-red right now, giving it a second kick

**Comment by pdehaan** [comment]
Did we change something in Travis recently? What's up with the two checks?

**Comment by 6a68** [comment]
I have no idea; the .travis.yml file hasn't been edited since the 6th, and I'm pretty sure I haven't seen that 2 checks thing until today.

**Pull request merged**
