### PR TITLE
chore(deps): Update grunt-sass dependency

### LINKED ISSUE #321: Chronicle doesn't install on Node 0.12
**TL;DR:** Don't install Node 0.12 yet.

---

I installed [**nvm**](https://github.com/creationix/nvm) and gave [Node 0.12](https://github.com/joyent/node/releases/tag/v0.12.0) a try, but it fails [hard] with the following spew:

```sh
> node-sass@1.2.3 install /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

> intern@2.2.2 install /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/intern
> node support/fixdeps.js

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/opt/nvm/versions/node/v0.12.0/bin/node" "/usr/local/opt/nvm/versions/node/v0.12.0/bin/npm" "i"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pdehaan/dev/tmp/chron12/chronicle/npm-debug.log
```

Looks like a **node-sass** issue (see https://github.com/sass/node-sass/issues/653) which should hopefully be fixed in **node-sass@2.0.0**, but not sure if there is an [ETA](https://github.com/sass/node-sass/issues/602) yet.

### PR DESCRIPTION
**Pull request by pdehaan**
Updating [**grunt-sass**](https://github.com/sindresorhus/grunt-sass/) ([CHANGELOG](https://github.com/sindresorhus/grunt-sass/compare/v0.17.0...v0.18.0)) and [**wreck**](https://github.com/hapijs/wreck/) ([CHANGELOG](https://github.com/hapijs/wreck/compare/v5.1.0...v5.2.0)) dependencies.

Chronicle should now run on iojs and Node 0.12! (tested w/ iojs-v1.2.0 and v0.12.0)!

Fixes #321

### CODE REVIEW

**Comment by pdehaan** [comment]
r? whomever wants to install nvm and iojs+node 0.12 (or whomever has the guts to blindly press the shiny green button).

**Comment by pdehaan** [comment]
Once/if this lands, we could also argue if we want to add Node 0.12 as a build target in the [travis.yml](https://github.com/mozilla/chronicle/blob/6f3b6489250b177fe68cebdca33691a9a333939e/.travis.yml#L4-L5) file.
Plus once Travis fixes https://github.com/travis-ci/travis-ci/issues/3108 we can specify an iojs target as well.

**Comment by 6a68** [comment]
@pdehaan Thanks for the PR, this is great! We don't actually use wreck anywhere, so it's best to remove it. Testing on v0.12 now ^_^

**Comment by 6a68** [comment]
works on 0.12, so remove the wreck dependency, then feel free to merge :-)

**Comment by pdehaan** [comment]
Doh! Totally forgot that I filed #331, _"Unused wreck and commander dependencies"_, the other day.

@6a68: Did you want me to remove **commander** dep while I'm at it, or are you planning on [adding that back in](https://github.com/mozilla/chronicle/blob/be914d43915eac936cdc21f9c8fe4628c6b45f5a/bin/migrate.js#L9)?

**Comment by pdehaan** [comment]
**wreck** removed (but still in shrinkwrap because it's a sub-dependency of something else).
I'll leave the **commander** module in the package.json since the comment in one of the /bin/* files implied that it would be making some sort of comeback in the future.

**Pull request merged**
