### PR TITLE
chore(build): Adding lint task to Travis

### LINKED ISSUE #303: Get "lint" task running on Travis
Looking at the [latest run on Travis](https://travis-ci.org/mozilla/chronicle/builds/49780638), it would seem that the log doesn't show any instances of "lint" or "jshint".

We should probably make sure that task gets run so there aren't any weird JSHint errors that may get merged and onto an auto-deploy dev/stage server. It shouldn't happen since the **precommit-hook** should run the link task locally before commiting (IIRC), but then suddenly #273.

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #303

### CODE REVIEW

**Comment by pdehaan** [comment]
Local testing shows that this adds 4-5s to the build process (but we'll wait to see what Travis thinks of this nonsense):
```sh
$ time npm run lint

> mozilla-chronicle@0.1.0 lint /Users/pdehaan/dev/github/chronicle
> grunt lint

...

Done, without errors.

real	0m4.580s
user	0m3.969s
sys  	0m0.316s
```

**Comment by pdehaan** [comment]
Other things I noticed aren't being automatically run are the silly `npm run outdated` and `npm run validate-shrinkwrap` tasks (which show "outdated" and risky modules, respectively).

```sh
$ npm run outdated && npm run validate-shrinkwrap

> mozilla-chronicle@0.1.0 outdated /Users/pdehaan/dev/github/chronicle
> npm outdated --depth 0

Package               Current  Wanted  Latest  Location
convict                 0.6.0   0.6.0   0.6.1  convict
embedly                 1.0.2   1.0.2   1.0.3  embedly
elasticsearch           3.1.1   3.1.1   3.1.3  elasticsearch
mozlog                  1.0.1   1.0.1   1.0.2  mozlog
underscore.string       3.0.1   3.0.1   3.0.2  underscore.string
url2png                 6.0.1   6.0.1   6.0.2  url2png
pg                      4.1.1   4.1.1   4.2.0  pg
node-resque            0.11.5  0.11.5  0.11.6  node-resque
grunt-contrib-jshint   0.10.0  0.10.0  0.11.0  grunt-contrib-jshint
bell                    2.0.0   2.0.0   2.1.0  bell
grunt-autoprefixer      2.1.0   2.1.0   2.2.0  grunt-autoprefixer
grunt-hapi              0.8.1   0.8.1   0.9.1  grunt-hapi
grunt-jscs              1.1.0   1.1.0   1.5.0  grunt-jscs
load-grunt-tasks        2.0.0   2.0.0   3.1.0  load-grunt-tasks

> mozilla-chronicle@0.1.0 validate-shrinkwrap /Users/pdehaan/dev/github/chronicle
> grunt validate-shrinkwrap --force

Running "validate-shrinkwrap" task
/Users/pdehaan/dev/github/chronicle/npm-shrinkwrap.json
>> Name  Installed  Patched  Vulnerable Dependency
>> qs      0.5.2     >= 1.x  mozilla-chronicle > embedly > superagent
>> qs      0.5.2     >= 1.x  mozilla-chronicle > embedly > superagent
>> qs      0.5.6     >= 1.x  mozilla-chronicle > url2png > request
>> qs      0.5.6     >= 1.x  mozilla-chronicle > url2png > request
Warning: known vulnerable modules found Used --force, continuing.

Done, but with warnings.
```

**Comment by pdehaan** [comment]
According to Travis timing metrics, adding `npm run lint` adds ~**5.4s** to the build time.
Adding the `npm run outdated` and `npm run audit-shrinkwrap` tasks would probably add another ~4s.

**Comment by 6a68** [comment]
I do think it's useful to use the same linter checks on travis that we use before committing locally.

I'm not as sure about the dependency check, though - we aren't in production yet, so I don't see the value in failing pull requests the moment any dependency becomes outdated. I'd actually suggest we just create a pre-release checklist that includes making sure we've updated dependencies. It should probably also include auditing all the changes in that release, and making sure spinning up a brand new box actually works before handing off to ops. We probably also want to make sure all the happy paths (sign up, sign in, create/destroy visit, get recent visits in sorted order, search) all work. @pdehaan you might have other things to add to this list, would you mind putting it together and submitting a PR adding this under `/docs`?

**Comment by pdehaan** [comment]
Sorry, just to clarify before we offtopic...
Yeah, `npm run outdated` and `npm run validate-shrinkwrap` wouldn't ever fail a build, they're only for personal interest sake (on some project's we _DO_ fail the build, but I don't like that model since it's often out of our control if Bower has bad devDependencies -- all we can do is file upstream bugs and hope they care).

But to address your questions, yes, I'll file a /docs PR which has a rough signoff checklist, and we can file any add-on bugs from there to maybe add `grunt release` tasks which generates changelogs and other bits.

**Comment by nchapman** [comment]
:+1:

**Comment by 6a68** [comment]
:beers: :cake: :neckbeard:

**Pull request merged**
