### PR TITLE
 style(dates): make date markers pretty

### PR DESCRIPTION
**Pull request by johngruen**
This should get merged after #340

### CODE REVIEW

**Comment by pdehaan** [comment]
chronicle
**Figure 1:** The bottom of the date marker is a bit touchy on the first history item.

**Comment by johngruen** [comment]
@pdehaan gap issue fixed!

**Comment by pdehaan** [comment]
Much nicer!
I'll need to tweak my local data some more since it seems to enter all the visits for the same day, but I did notice a super edge case where you spend 4 minutes deleting all your visits, the date header still remains. But we can file that as a separate issue and handle it later.

chronicle
**Figure 2:** Date header remains after you delete all your visits.

**Comment by pdehaan** [comment]
Possibly less edge case? I hacked my ./bin/create_test_data.js to create data for random days and then I deleted items and it looks roughly like this. Actually, probably the same issue as my previous comment, just funnier results with multiple stacked day labels:

chronicle
**Figure 3:** January 4th January 3rd January 2nd

**Comment by nchapman** [comment]
Hooray! :+1:

**Comment by nchapman** [comment]
> Date header remains after you delete all your visits.

@pdehaan will you create a new issue for this?

**Comment by pdehaan** [comment]
@nchapman Filed as #350

**Pull request merged**
